<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Rudranshlaptop" failures="0" tests="9" name="Project_cognizant.Test_function" time="2.386" errors="1" timestamp="2023-05-20T01:14:14 IST" skipped="0">
  <testcase classname="Project_cognizant.Test_function" name="open_page" time="0.881"/>
  <system-out/>
  <testcase classname="Project_cognizant.Test_function" name="car_type" time="0.001">
    <error message="Unresolved compilation problem: 
	Unhandled exception type InterruptedException
" type="java.lang.Error">
      <![CDATA[java.lang.Error: Unresolved compilation problem: 
Unhandled exception type InterruptedException

at Project_cognizant.Test_function.car_type(Test_function.java:89)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- car_type -->
  <system-out/>
  <testcase classname="Project_cognizant.Test_function" name="colour" time="0.188"/>
  <system-out/>
  <testcase classname="Project_cognizant.Test_function" name="click" time="0.158"/>
  <system-out/>
  <testcase classname="Project_cognizant.Test_function" name="sensor" time="0.155"/>
  <system-out/>
  <testcase classname="Project_cognizant.Test_function" name="help" time="0.256"/>
  <system-out/>
  <testcase classname="Project_cognizant.Test_function" name="chat" time="0.243"/>
  <system-out/>
  <testcase classname="Project_cognizant.Test_function" name="visit" time="0.339"/>
  <system-out/>
  <testcase classname="Project_cognizant.Test_function" name="validation" time="0.165"/>
  <system-out/>
</testsuite> <!-- Project_cognizant.Test_function -->
